apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-management
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-management
  template:
    metadata:
      labels:
        app: task-management
    spec:
      containers:
      - name: task-management
        image: 727646487669.dkr.ecr.us-west-2.amazonaws.com/task-management:latest
        ports: 
        - containerPort: 3000
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
